name: test

on:
  push:
    branches:
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:

jobs:

  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
        include:
          - os: windows-latest
            version: '1'
          - os: macOS-latest
            version: '1'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          show-versioninfo: true
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@latest
        if: "matrix.version == 'nightly' && matrix.os == 'ubuntu-latest'"
      - uses: codecov/codecov-action@v1
        if: "matrix.version == 'nightly' && matrix.os == 'ubuntu-latest'"
        with:
          file: lcov.info
      - name: Install benchmark dependencies
        if: "matrix.version == 'nightly' && matrix.os == 'ubuntu-latest'"
        run: julia -e 'using Pkg; pkg"add PkgBenchmark BenchmarkCI@0.1"'
      - name: Run benchmarks
        if: "matrix.version == 'nightly' && matrix.os == 'ubuntu-latest'"
        run: julia -e 'using BenchmarkCI; BenchmarkCI.judge(baseline="origin/main")'
      - name: Post benchmark results
        if: "matrix.version == 'nightly' && matrix.os == 'ubuntu-latest'"
        run: julia -e 'using BenchmarkCI; BenchmarkCI.postjudge()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
